name: Flutter
on: push

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.20.4'
    - run: flutter pub get
    - run: flutter analyze
    - run: flutter test

  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.20.4'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --split-per-abi
    - run: flutter build ios --release --no-codesign
    - name: Create Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/debug/*.apk"
        token: ${{ secrets.TOKEN }}